# Generated by Django 5.0.6 on 2024-12-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('party', models.CharField(max_length=50)),
                ('voteNum', models.IntegerField()),
                ('votePcnt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StatePollingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('party_winner', models.CharField(max_length=50)),
                ('total_votes', models.IntegerField()),
                ('electoralVotes', models.IntegerField()),
                ('candidates', models.ManyToManyField(related_name='states', to='api.candidate')),
            ],
        ),
    ]
