# Generated by Django 5.0.6 on 2025-01-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_candidate_name_candidate_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='fill',
            field=models.CharField(default='var(--color-Unknown)', max_length=50),
        ),
    ]
